version = 0.1
[default.deploy.parameters]
stack_name = "backend-example-template-aws-juanp"
resolve_s3 = true
s3_prefix = "backend-example-template-aws-juanp"
region = "us-east-1"
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
parameter_overrides = "AppName=\"app-juanp\" AppEnv=\"dev\""
image_repositories = []
